In [1]:
# Numpy is  a fundamental package for data sciend in python

In [2]:
# Numpy package gives a new data types for handing data in python called as " N-D ARRAY"
# This stands for N- Dimensional Arrays

In [3]:
# till now we have stuided about: List, Int, Tuples, Strings, out of which the data types such as
# List,Tuples have been used to store data and Range used for generating new data(sequential).
# There should be a question: Why do we need a new data type to work with Data Science.
# So numpy essentially is build on top of C language which is compatible with Python.
# It leverage the powe of closness of C with Hardware which eventually makes the processing laster in python.
# The above is about the PERFORMACE OF PYTHON

In [4]:
# Memory Efficiency: Arrays created by NUMPY is Python are less memorty exhausitive than Lists in Python.
# In list, each item is an obkect and it holds meta information in like reference and types. etc This makes
# list consume more memory.

# But Arrays in Munpys are contigios, which means that they do not create object but rather directs store the
# data in continous memory blocks on after another, Aslo the arrays are homogeneous in nature.

In [5]:
# Arrays are basically vactorised operations and they are ways more convienient to
# deal with as compared to list in python.

In [6]:
# They the most important, other packages which are Pands, Metplotlib, Seaborm, Sklearn, Scipy all are written on to
# all are written on top of Numpy paackage. For this reason its called as Fundamental package.

In [7]:
# All these packages make out Data Science Journey smooth because we have to worry less about code and more about logic

In [8]:
# Lets get started.

In [9]:
# So to import the package Numnpy
import numpy as np # Where "np" is an alias

In [10]:
pip install numpy # Python Index package - Play store, App store, Windows store for Python | Package Manager

Note: you may need to restart the kernel to use updated packages.


In [11]:
 np.__version__

'2.5.3'

In [12]:
# Numpy is an open source package and if you want to see the code -- github

In [13]:
# We have multiple diamension in arrays - 0D,1D,2D,3D....N-D Arrays

In [14]:
# 0 - Dimension Array
arr0 = np.array(2)
print(type(arr0))
print(arr0.ndim)
print(arr0.shape)

<class 'numpy.ndarray'>
0
()


In [15]:
# Check the dimension
print(arr0.ndim) # This is a SCALAR

0


In [16]:
# List 
lis = [11,22,33,44]
print(type(lis))

<class 'list'>


In [17]:
# I will create a 1 - Dimension Array from list
arr1 = np.array(lis)
print(arr1)
print(type(arr0))

# Check the dimension
print(arr1.ndim) # This is a SCALAR
print(arr1.shape)

[11 22 33 44]
<class 'numpy.ndarray'>
1
(4,)


In [18]:
# I will create a 2 - Dimension array from a "Nested" list
lis2 = [[11,22,33],[44,55,66],[77,88,99]]
arr2 = np.array(lis2)
print(arr2)
print(type(arr2))

#Check a dimension
print(arr2.ndim)
print(arr2.shape)

[[11 22 33]
 [44 55 66]
 [77 88 99]]
<class 'numpy.ndarray'>
2
(3, 3)


In [19]:
# I will create a 3 - Dimension array from a "Nested" list
lis3 = [[[11,22,33],[44,55,66],[77,88,99]],[[111,222,333],[444,555,666],[777,888,999]]] # Marks of 3 different students
arr3 = np.array(lis3)
print(arr3)
print(type(arr3))

# Check a dimension
print(arr3.ndim)
print(arr3.shape)

[[[ 11  22  33]
  [ 44  55  66]
  [ 77  88  99]]

 [[111 222 333]
  [444 555 666]
  [777 888 999]]]
<class 'numpy.ndarray'>
3
(2, 3, 3)


In [20]:
# Multiple ways ti create arrays
# 1. From list
# 2. Zero list
# 3. Ones list
# 4. Custom list

In [21]:
# Zeroes Array

zero_arr1 = np.zeros(2)
print(zero_arr1) # (1,2)
print(zero_arr1.ndim)
print(zero_arr1.shape)

[0. 0.]
1
(2,)


In [22]:
zero_arr2 = np.zeros((2,1))
print(zero_arr2)
print(zero_arr2.ndim)
print(zero_arr2.shape)

[[0.]
 [0.]]
2
(2, 1)


In [23]:
zero_arr210 = np.zeros((10,10))
print(zero_arr210)
print(zero_arr210.ndim)
print(zero_arr210.shape)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
2
(10, 10)


In [24]:
zero_arr3 = np.zeros((4,3,3)) # No. of Layers, No. of Rows, No. of Columns

In [25]:
zero_arr3
print(zero_arr3.shape)

(4, 3, 3)


In [26]:
# Represent an an image with (RGB channel and 256 256)
img = np.zeros((3,256,256))
img

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]], shape=(3, 256, 256))

In [27]:
# You can also create array with ones

a1 = np.ones(2)
a1

array([1., 1.])

In [28]:
# Create 2 dimension and 3 dimension of arrays of 1
a2 = np.ones((2,2))
a2

array([[1., 1.],
       [1., 1.]])

In [29]:
a3 = np.ones((3,3,3))
a3

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [30]:
# Custom arrays

In [31]:
custom_arr = np.full((6,6),"K")
custom_arr

array([['K', 'K', 'K', 'K', 'K', 'K'],
       ['K', 'K', 'K', 'K', 'K', 'K'],
       ['K', 'K', 'K', 'K', 'K', 'K'],
       ['K', 'K', 'K', 'K', 'K', 'K'],
       ['K', 'K', 'K', 'K', 'K', 'K'],
       ['K', 'K', 'K', 'K', 'K', 'K']], dtype='<U1')

In [32]:
custom_arr2 = np.full((6,6),9.87)
custom_arr2

array([[9.87, 9.87, 9.87, 9.87, 9.87, 9.87],
       [9.87, 9.87, 9.87, 9.87, 9.87, 9.87],
       [9.87, 9.87, 9.87, 9.87, 9.87, 9.87],
       [9.87, 9.87, 9.87, 9.87, 9.87, 9.87],
       [9.87, 9.87, 9.87, 9.87, 9.87, 9.87],
       [9.87, 9.87, 9.87, 9.87, 9.87, 9.87]])

In [33]:
# How did we use range in python? Can you range to generate number between 20-50

r = range(20,51)
for i in r:
    print(i)

20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50


In [34]:
# Similar to range in python , we have ARANGE in NUMPY

arange_arr = np.arange(20,51)
arange_arr

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [35]:
arange_arr1 = np.arange(20,51,3)
arange_arr1

array([20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

In [36]:
# Range in python = Aragne in numpy

# Linspace -- It stands for linear spacing which mean between 2 given numbers
# this function will fit the required no of numbers

# We need to create an interval from 0 - 10  and want to have 10 numbers in it.

linspace = np.linspace(0,1,100) # That from 0-1 give me 100 numbers equally spaced numbers
linspace

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [37]:
# Now suppose we want to generate random numbers

# Random, Random -- will generate random float numbers betweem 0-1

rand_rand = np.random.random((6,6))
rand_rand

array([[0.2587274 , 0.57151164, 0.83572534, 0.16957841, 0.04472762,
        0.32804989],
       [0.86943327, 0.27218186, 0.53731106, 0.05518982, 0.04052497,
        0.27438013],
       [0.4494975 , 0.77024449, 0.80220835, 0.44892142, 0.5794634 ,
        0.14366856],
       [0.17166616, 0.4925322 , 0.00938331, 0.28982651, 0.77841555,
        0.85126897],
       [0.8699241 , 0.3602153 , 0.94895388, 0.68625692, 0.81191867,
        0.73154483],
       [0.48965919, 0.23585702, 0.63085939, 0.12731269, 0.6737588 ,
        0.91541389]])

In [38]:
100 * rand_rand

array([[25.87273981, 57.15116399, 83.57253406, 16.95784079,  4.47276175,
        32.80498871],
       [86.9433275 , 27.21818635, 53.73110598,  5.51898158,  4.05249653,
        27.43801292],
       [44.94974964, 77.02444886, 80.22083471, 44.8921417 , 57.94634032,
        14.36685643],
       [17.16661566, 49.25322003,  0.93833075, 28.98265105, 77.84155536,
        85.12689677],
       [86.99240997, 36.02153002, 94.89538776, 68.62569232, 81.19186696,
        73.15448335],
       [48.96591932, 23.58570237, 63.08593935, 12.73126903, 67.37588018,
        91.54138876]])

In [39]:
# We can also create random integers

randint = np.random.randint(20,25,(3,3))
randint

array([[24, 22, 22],
       [20, 21, 20],
       [21, 22, 24]])

In [40]:
# Properties and Attributes of Numpy Arrays

# 1. Shape of Array -- It tells you the Dimensions of the array stored in a tuple.

print(arr0.shape)
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

()
(4,)
(3, 3)
(2, 3, 3)


In [41]:
# 2. ndim of array -- It tell you the rank of the array

print(arr0.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

0
1
2
3


In [42]:
# 3. Size of array -- It tells you the Number of element inside array.

print(arr0.size)
print(arr1.size)
print(arr2.size)
print(arr3.size)

1
4
9
18


In [43]:
# 4. dtype of array -- tells you the datatypes of the array {Only of homogenous data in Array}

print(arr0.dtype)
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

int64
int64
int64
int64


In [44]:
arr_hetrogenous = np.array([11,22,33,44,55,66,77])
arr_hetrogenous.dtype

dtype('int64')

In [45]:
arr_hetrogenous1 = np.array([11,22,33,44,55,66,77,"Ram"])
arr_hetrogenous1.dtype

dtype('<U21')

In [46]:
# 5. Item size of array -- it gives you the byte occupies by each element of an array

print(arr1.itemsize," Bytes")

# The result is 8 Bytes because each element in arr1 is occupying 64 bits which are equivalent to 8 Bytes

8  Bytes


In [47]:
# 6. nbytes of an array -- will give you the total bytes occupies by the elements of the array

print(arr1.nbytes,"Bytes")

32 Bytes


In [48]:
# 7. astype in array -- this will help you change the datatypes of the array

print("Array", arr1)
print("Dtype of Array", arr1.dtype)

arr1 = arr1.astype(np.int32)

print("Array", arr1.dtype)
print("Dtype of array", arr1.dtype)

arr1 = arr1.astype(np.float64)

print("Array", arr1)
print("Dtype of Array", arr1.dtype)

arr1 = arr1.astype(np.int16)

print("Array",arr1)
print("Dtype of Array", arr1.dtype)

arr1 = arr1.astype(np.int8)

print("Array", arr1)
print("Dtype of Array", arr1.dtype)

Array [11 22 33 44]
Dtype of Array int64
Array int32
Dtype of array int32
Array [11. 22. 33. 44.]
Dtype of Array float64
Array [11 22 33 44]
Dtype of Array int16
Array [11 22 33 44]
Dtype of Array int8


In [49]:
# you can define the dtypes of the array while creation time also

arr11 = np.array([11,22,33,44],dtype = "float32")
arr11

array([11., 22., 33., 44.], dtype=float32)

In [50]:
# Methods on Numpy Arrays

In [51]:
# 1. reshape --> you can use this to create a new shaoe if the array.
# Suppose we have a 1 D array of 20 elements.
# Now to reshape it, we need to find the factors of 20 : 1,20,4,5,2,10

random_arr = np.random.randint(1,50,(20))
random_arr

array([ 8,  2, 13, 10, 35,  4, 29, 18,  2,  6, 45, 41,  5, 42, 34, 45, 12,
       22, 21, 48])

In [52]:
# Now reshape

# First i will reshape in (1,20)

print("================2-D===================")

print(random_arr.reshape((1,20)))

print("================2-D===================")

print(random_arr.reshape((20,1)))

print("================2-D===================")

print(random_arr.reshape((2,10)))

print("================2-D===================")

print(random_arr.reshape((10,2)))

print("================2-D===================")

print(random_arr.reshape((4,5)))

print("================3-D===================")

print(random_arr.reshape((2,2,5)))

print("================3-D===================")

print(random_arr.reshape((5,2,2)))

print("================3-D===================")

print(random_arr.reshape((10,2,1)))


================2-D===================
[[ 8  2 13 10 35  4 29 18  2  6 45 41  5 42 34 45 12 22 21 48]]
================2-D===================
[[ 8]
 [ 2]
 [13]
 [10]
 [35]
 [ 4]
 [29]
 [18]
 [ 2]
 [ 6]
 [45]
 [41]
 [ 5]
 [42]
 [34]
 [45]
 [12]
 [22]
 [21]
 [48]]
================2-D===================
[[ 8  2 13 10 35  4 29 18  2  6]
 [45 41  5 42 34 45 12 22 21 48]]
================2-D===================
[[ 8  2]
 [13 10]
 [35  4]
 [29 18]
 [ 2  6]
 [45 41]
 [ 5 42]
 [34 45]
 [12 22]
 [21 48]]
================2-D===================
[[ 8  2 13 10 35]
 [ 4 29 18  2  6]
 [45 41  5 42 34]
 [45 12 22 21 48]]
================3-D===================
[[[ 8  2 13 10 35]
  [ 4 29 18  2  6]]

 [[45 41  5 42 34]
  [45 12 22 21 48]]]
================3-D===================
[[[ 8  2]
  [13 10]]

 [[35  4]
  [29 18]]

 [[ 2  6]
  [45 41]]

 [[ 5 42]
  [34 45]]

 [[12 22]
  [21 48]]]
================3-D===================
[[[ 8]
  [ 2]]

 [[13]
  [10]]

 [[35]
  [ 4]]

 [[29]
  [18]]

 [[ 2]
  [ 6]]

 [

In [53]:
# 2. transpose --> Iter Change the dimension like rows and columns

arr2

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [54]:
arr2_t = arr2.transpose()
arr2_t

array([[11, 44, 77],
       [22, 55, 88],
       [33, 66, 99]])

In [55]:
random_arr = random_arr.reshape((2,10))
random_arr

array([[ 8,  2, 13, 10, 35,  4, 29, 18,  2,  6],
       [45, 41,  5, 42, 34, 45, 12, 22, 21, 48]])

In [56]:
random_arr_t = random_arr.transpose()
random_arr_t

array([[ 8, 45],
       [ 2, 41],
       [13,  5],
       [10, 42],
       [35, 34],
       [ 4, 45],
       [29, 12],
       [18, 22],
       [ 2, 21],
       [ 6, 48]])

In [57]:
# 3. Flatten -- It reduces the dimension to 1 D

random_arr_t

array([[ 8, 45],
       [ 2, 41],
       [13,  5],
       [10, 42],
       [35, 34],
       [ 4, 45],
       [29, 12],
       [18, 22],
       [ 2, 21],
       [ 6, 48]])

In [58]:
random_arr_t_f = random_arr_t.flatten()
random_arr_t_f

array([ 8, 45,  2, 41, 13,  5, 10, 42, 35, 34,  4, 45, 29, 12, 18, 22,  2,
       21,  6, 48])

In [59]:
# Example 2:
random_arr = np.random.randint(1,50,(20)).reshape(5,2,2)
random_arr

array([[[ 5, 43],
        [ 1,  5]],

       [[14, 49],
        [ 8, 22]],

       [[38,  8],
        [19,  3]],

       [[40, 23],
        [11, 10]],

       [[29, 24],
        [38, 29]]])

In [60]:
random_arr_f = random_arr.flatten()

In [61]:
random_arr_f

array([ 5, 43,  1,  5, 14, 49,  8, 22, 38,  8, 19,  3, 40, 23, 11, 10, 29,
       24, 38, 29])

In [62]:
# Let me now show you the power of Numpy over List and other data types

In [63]:
# I Told you that List take up much more memory as compared to Numpy Arrays

ran = range(10000)

In [64]:
# I will use Arange in numpy to create a similar series of numbers

array = np.arange(10000)

In [65]:
import sys

In [66]:
# get size of --- method which calculates the bytes occupied by a single element in vanila python

print(sys.getsizeof(5),"Bytes")

28 Bytes


In [67]:
# 28 bytes are occupies by one element of range

In [68]:
# How many numbers range has ? == 10000
# Total menory occupied will be ?
# 28 * 10000 = 280000
print(sys.getsizeof(5) * len(ran),"Bytes")

280000 Bytes


In [69]:
 # Using nbyes for arrays
print(array.nbytes, "Bytes")

80000 Bytes


In [70]:
# Performance

import time

In [71]:
x = range(1000000) # 10 milion values
y = range(1000000,2000000) # 10 milion valuies


In [72]:
start_time = time.time() # This will give you the cuirrent time
c = [x+y for x,y in zip(x,y)] # Add the element of "x" and "y" element by element
print(time.time() - start_time, "Seconds") # Will give me delta of time & time taken for operation


0.20514631271362305 Seconds


In [73]:
# Arrays

a = np.arange(1000000)
b = np.arange(1000000,2000000)

In [74]:
start_time = time.time()
c = a + b
print(time.time() - start_time, "Seconds")

0.051610708236694336 Seconds


In [75]:
x = range(5) # 0,1,2,3,4
y = range(5,10)
c = [x + y for x, y in zip(x, y)]
print(c)

[5, 7, 9, 11, 13]


In [76]:
a = np.arange(5)
b = np.arange(5,10)
c = a + b
c

array([ 5,  7,  9, 11, 13])

In [77]:
# Indexing in numpy Arrays

In [78]:
# For 1 D arrays

In [79]:
arr1

array([11, 22, 33, 44], dtype=int8)

In [80]:
# I want to Dice 33
# Index of 33 is 2

print(arr1[2])

33


In [81]:
# If you wish to slice 33 - 66
# Index 2:6

print(arr1[2:6])

[33 44]


In [82]:
# Indexing to 2D arrays

arr2

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [83]:
# Indexing first row
print(arr2[0],"Row1")
print(arr2[1],"Row2")
print(arr2[2],"Row3")

print(arr2[:,0],"Col1")
print(arr2[:,1],"Col2")
print(arr2[:,2],"Col3")


[11 22 33] Row1
[44 55 66] Row2
[77 88 99] Row3
[11 44 77] Col1
[22 55 88] Col2
[33 66 99] Col3


In [84]:
# Particular element 88
print(arr2[2,1])

88


In [85]:
# Slcing through the array: 55,66,88,99
print(arr2[1:,1:])

[[55 66]
 [88 99]]


In [86]:
# Check it for 3D - SYNTAX: array[Layer, Row, Column]
arr3

array([[[ 11,  22,  33],
        [ 44,  55,  66],
        [ 77,  88,  99]],

       [[111, 222, 333],
        [444, 555, 666],
        [777, 888, 999]]])

In [87]:
print(arr3[1,1,1])
print(arr3[0,1,2])

555
66


In [88]:
# Operations on Arrays

In [89]:
# List
l= [1,2,3,4,5]

# Square each element of the list

sq_l = [x**2 for x in l]
print("Orignal List",l)
print("Squared List",sq_l)

Orignal List [1, 2, 3, 4, 5]
Squared List [1, 4, 9, 16, 25]


In [90]:
# Now in array

a1 = np.array(l)

print("Original Array",a1)

# Square the elements of array

Sq_a1 = a1 ** 2
print("Squared Array",Sq_a1)

Original Array [1 2 3 4 5]
Squared Array [ 1  4  9 16 25]


In [91]:
# Suppose you want to find the mean of numbers using list
mean = sum(l) / len(l)

In [92]:
mean

3.0

In [93]:
# You can perform some String operation

In [94]:
# I have an array of names of people

names = np.array(["ram","syam","hari"])

In [95]:
names

array(['ram', 'syam', 'hari'], dtype='<U4')

In [96]:
# You wish to capitalize the names

print(np.char.capitalize(names))

['Ram' 'Syam' 'Hari']


In [97]:
# Upper
print(np.char.upper(names))

['RAM' 'SYAM' 'HARI']


In [98]:
print(np.char.lower(names))

['ram' 'syam' 'hari']


In [99]:
title = np.array(["ram goal","dinesh senapati","hari verma"])

In [100]:
print(np.char.title(title))

['Ram Goal' 'Dinesh Senapati' 'Hari Verma']


In [101]:
# I can also replace somthing

print(np.char.replace(title,"ram","surbhi"))

['surbhi goal' 'dinesh senapati' 'hari verma']


In [102]:
# Calculate the char of string
print(np.char.str_len(title))

[ 8 15 10]


In [103]:
f_name = np.array(["Hari","Ram","Shiva"])
l_name = np.array(["Gurung","Thapa","Sharma"])

In [104]:
full_name = np.char.add(f_name, l_name)

In [105]:
full_name

array(['HariGurung', 'RamThapa', 'ShivaSharma'], dtype='<U11')

In [106]:
a

array([0, 1, 2, 3, 4])

In [107]:
# You can find an element through a letter
print(np.char.find(full_name,"Ra") >= 0)

[False  True False]
